# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a4faf4e31b3a8e8f5ccd8983361bc97bc96dfd727464dde47f6b0dec5b7e939164a69ecf7d21e240ca6489304512b0ea90591b08868f6ac6f201f820fa8fb7

test:
  secret_key_base: d78d6b63d0f871072dabba429356277f700bd361599cf41853a4ec23176ce05fe2de8f67d6ec63b41b95692813833c3078831ad4a59534c374e586430af5d5d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
